ci:
  autofix_prs: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-json
    exclude: "\\.vscode/.*.json"
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.12.8
  hooks:
  - id: ruff-check
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - id: ruff-format
