[build-system]
build-backend = "hatchling.build"

requires = [ "hatchling" ]

[project]
name = "tap-mailchimp"
version = "0.0.1"
description = "Singer tap for Mailchimp, built with the Meltano SDK for Singer Taps."
keywords = [
  "ELT",
  "Mailchimp",
]
license = "Apache-2.0"
authors = [ { name = "Edgar Ramírez-Mondragón", email = "edgarrm358@gmail.com" } ]
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "requests-cache==1.2.*",
  "singer-sdk==0.48.*",
  "toolz==0.12.*",
]

scripts.tap-mailchimp = "tap_mailchimp.tap:TapMailchimp.cli"

[dependency-groups]
dev = [
  { include-group = "testing" },
]
ci = [
  "pytest-github-actions-annotate-failures>=0.3",
]
testing = [
  "pytest~=8.4",
]

[tool.ruff]
target-version = "py310"
line-length = 88
src = [ "noxfile.py", "tap_mailchimp", "tests" ]
lint.select = [ "ALL" ]
lint.ignore = [ "DJ", "PD" ]
lint.per-file-ignores."noxfile.py" = [ "ANN" ]
lint.per-file-ignores."tests/*" = [ "ANN" ]
lint.isort.known-first-party = [ "tap_mailchimp" ]
lint.pydocstyle.convention = "google"

[tool.pyproject-fmt]
max_supported_python = "3.14"
