[tool.poetry]
name = "tap-mailchimp"
version = "0.0.1"
description = "`tap-mailchimp` is a Singer tap for Mailchimp, built with the Meltano SDK for Singer Taps."
authors = [
    "Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"
]
keywords = [
    "ELT",
    "Mailchimp",
]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.7.1,<4"
singer-sdk = "==0.33.*"
toolz = "==0.12.*"
requests-cache = "==1.1.*"

[tool.poetry.dev-dependencies]
pytest = "~=7.4"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_mailchimp"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-mailchimp = 'tap_mailchimp.tap:TapMailchimp.cli'

[tool.ruff]
line-length = 88
src = ["tap_mailchimp", "tests", "noxfile.py"]
target-version = "py37"

[tool.ruff.lint]
ignore = ["ANN101", "DJ", "PD"]
select = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["tap_mailchimp"]

[tool.ruff.lint.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = ["ANN"]

[tool.ruff.lint.pydocstyle]
convention = "google"
