[tool.poetry]
name = "tap-mailchimp"
version = "0.0.1"
description = "`tap-mailchimp` is a Singer tap for Mailchimp, built with the Meltano SDK for Singer Taps."
authors = [
    "Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"
]
keywords = [
    "ELT",
    "Mailchimp",
]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8,<4"
singer-sdk = "==0.33.*"
toolz = "==0.12.*"
requests-cache = "==1.1.*"

[tool.poetry.dev-dependencies]
pytest = "~=7.4"
singer-sdk = { version = "==0.33.*", extras = ["testing"] }

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-mailchimp = 'tap_mailchimp.tap:TapMailchimp.cli'

[tool.ruff]
line-length = 88
src = ["tap_mailchimp", "tests", "noxfile.py"]
target-version = "py37"

[tool.ruff.lint]
ignore = [
  "ANN101",  # missing-type-self
  "DJ",      # flake8-django
  "PD",      # pandas-vet
  "COM812",  # missing-trailing-comma
  "ISC001",  # single-line-implicit-string-concatenation
]
select = ["ALL"]

[tool.ruff.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.isort]
known-first-party = ["tap_mailchimp"]

[tool.ruff.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = ["ANN"]

[tool.ruff.pydocstyle]
convention = "google"
