[tool.poetry]
name = "tap-mailchimp"
version = "0.0.1"
description = "`tap-mailchimp` is a Singer tap for Mailchimp, built with the Meltano SDK for Singer Taps."
authors = [
    "Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"
]
keywords = [
    "ELT",
    "Mailchimp",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
singer-sdk = "==0.4.4"
toolz = "==0.11.2"
requests-cache = "==0.9.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
tox = "^3.24.5"
flake8 = "^4.0.1"
black = "^22.1"
pydocstyle = "^6.1.1"
mypy = "^0.931"
types-requests = "^2.27.12"
isort = "^5.9.3"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_mailchimp"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-mailchimp = 'tap_mailchimp.tap:TapMailchimp.cli'
